# Generated by Django 2.0.6 on 2019-02-27 21:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=10000)),
                ('created_date', models.DateField(verbose_name=django.utils.timezone.now)),
                ('published_date', models.DateField(verbose_name=django.utils.timezone.now)),
            ],
        ),
    ]
